
%%
clear all
close all

% Set location of data
datadir = '../../Data/';
rootdir = '../../journal paper draft/';
foreps = 'D:/';
epsdir = 'C:\Users/Asus/Desktop/journal_photoshop\exp\leadindex\late\';
epsdir = '../../Data/eps/new/panel_sep/';

 resdir = [datadir, 'results/'];
 figdir = [datadir, 'figs/'];
% epsdir = [foreps, 'eps/'];


% Details on subjects

haptic_group={...
       'K_S';... 
       'L_J';... 
       'P_At';...
       'P_A';...
       'M_F';...
       };

% haptic_group = { 'EC_AV'; } ;
NH = size(haptic_group,1)

visuohaptic_group={...
       'N_F';...
       'Z_A';...
       'P_C';...
       'A_J';...
       'P_O';...
       'S_N';...
    };

% visuohaptic_group={...
%        'Z_A';...
%        'P_C';...
%        'M_F';...
%        'P_A';...
%        'S_N';...
%     };

% visuohaptic_group = { 'EC_AV_dummy'; } ;
NVH = size(visuohaptic_group,1);

partnervisible_group={...
       'M_N';...
       'S_D';...
       'A_N';...
       'C_N';...
       'N_R';...
     
    };

% visuohaptic_group = { 'EC_AV_dummy'; } ;
PV = size(partnervisible_group,1);

% groups = {'H','VH'};
groups = {'H','VH', 'PV'};
% subjects.names = [haptic_group;visuohaptic_group];
subjects.names = [haptic_group;visuohaptic_group;partnervisible_group];
% subjects.groups=[ones(NH,1);2*ones(NVH,1)]; % groups are 1,2,...
subjects.groups=[ones(NH,1);2*ones(NVH,1);3*ones(PV,1)]; % groups are 1,2,...
subjects.datadir = datadir; 
subjects.datadir = datadir; 

 % Data format
data_format = {...
         'time',...          % if H3D may be two fields
         'traj1_x',...       % this is S1 trajectory (x,y,z)
         'traj1_y',...       % this is S1 trajectory (x,y,z)
         'traj1_z',...       % this is S1 trajectory (x,y,z)        
         'traj2_x',...       % this is S2 trajectory (x,y,z)
         'traj2_y',...       % this is S2 trajectory (x,y,z)
         'traj2_z',...       % this is S2 trajectory (x,y,z)     
         'force1_x',...  
         'force1_y',... 
         'force1_z',...       
         'force2_x',...  
         'force2_y',... 
         'force2_z',...       
         'state',...% this is state of experimental protocol (from FSM)  
     };
 
 data_format = {...
         'time',...          % if H3D may be two fields
         'traj2_x',...       % this is S2 trajectory (x,y,z)
         'traj2_y',...       % this is S2 trajectory (x,y,z)
         'traj2_z',...       % this is S2 trajectory (x,y,z)        
         'traj1_x',...       % this is S1 trajectory (x,y,z)
         'traj1_y',...       % this is S1 trajectory (x,y,z)
         'traj1_z',...       % this is S1 trajectory (x,y,z)     
         'force2_x',...  
         'force2_y',... 
         'force2_z',...       
         'force1_x',...  
         'force1_y',... 
         'force1_z',...       
         'state',...% this is state of experimental protocol (from FSM)  
     };
 data_format1 = {...
                 'time',...
                 'score1',...
                 'score2',...
                 };
                 
 data_format2 = {...
                 'time',...
                 'score2',...
                 'score1',...
                 };
 
 % Details on protocol
protocol.groupdesc=groups;
 protocol.phases = {'baseline','training','aftereffect'}; 
%   protocol.phases = {'baseline','training-early','training-final','aftereffect'}; 
% protocol.order = {1:2,3:15,16:18};  % target sets in experiment 
 protocol.order = {1,2:11,12:13};
%  protocol.order = {1,2,11,12};

protocol.dataprefix = 'visuohaptic';
protocol.data_format = data_format;
protocol.data_format1 = data_format1;
protocol.data_type = 'CHAI3D';

% Details on task
task.type = 'dyad';  % could also be 'bimanual','unimanual' CHECK!!!
task.fc = 100;
task.Ntargets = 1;
task.tgsize = 0.005; %  1 cm diameter
amplitude = 0.10;
task.targets = [amplitude 0 0]; % XYZ coordinate of target  CHECK!!!
task.expmode = 'fwd';              

%% asymmetric via positions
task.viapoints = [0 0.03 -0.03;... % this is VP1 (closest to start)
                  0 0.07 0.03; ... % this is VP2 (closest to end)           
                ];   

% symmetric via positions 
%  task.viapoints =[0 0.0455 -0.03;... % this is VP1 (closest to start)
%                   0 0.0505 0.03; ... % this is VP2 (closest to end)           
%                  ];   

% protocol.phases = {'baseline','training','aftereffect'}; 
 %protocol.phases = {'baseline','training-early','training-final','aftereffect'}; 
 %protocol.order = {1,2,11,12};  % target sets in experiment 

% construct experiment object
%  exper=experiment(subjects,protocol,task,@get_runs_dyad);  %runs=data.ct direttamente da get runs
 [scores,exper]=experiment(subjects,protocol,task,@get_runs_dyad);  %runs=data.ct direttamente da get runs

% [lead11, lead12, lead21, lead22] = plot(subj,{'leadership'},figdir,epsdir,@plot_more)

%% Plot movements of dyad
%plot_bysubject(exper,{'traj','speed'},figdir,epsdir,@plot_more)
%plot_bysubject(exper,{'speed'},figdir,epsdir)
%plot_bysubject(exper,{'speed','variability','power'},figdir,epsdir,@plot_more)
%plot_bysubject(exper,{'int_force'},figdir,epsdir,@plot_more)
%plot_bysubject(exper,{'power'},figdir,epsdir,@plot_more)
%plot_bysubject(exper,{'min_viadist'},figdir,epsdir,@plot_more)
% plot_bysubject(exper,{'leadership'},figdir,epsdir,@plot_more)
%plot_bysubject(exper,{'traj'},figdir,epsdir,@plot_more)

%plot_bysubject(exper,{'speed'},figdir,epsdir,@plot_more)
%plot_bys ubject(exper,{'speed','speed_corr'},figdir,epsdir,@plot_more)
%plot_bysubject(exper,{'variability'},figdir,epsdir,@plot_more)
%plot_bysubject(exper,{'trajforce'},figdir,epsdir,@plot_more)


% [lead11, lead12, lead21,  lead22] = plot(subj,displist,figdir,epsdir,varargin);
% fprintf(file1,'%f\t%f\t\n',lead11, lead12);
% fprintf(file2,'%f\t%f\t\n',lead21,lead22);

%% Save all indicator data on files
% Define indicators
indlist = {'ts1',...
           'ts2',...
           'te1',...
           'te2',...
           'md11',...
           'md12',...
           'md22',...
           'md21',...
           'tc11',...
           'tc12',...
           'tc22',...
           'tc21',...
           'eff1',...
           'eff2',...
           'pow1',...
           'pow2',...
           'pow11',...
           'pow22',...
           'pow12',...
           'pow21',...
           'tp1',...
           'tp2',...
           'lead1',...
           'lead2',...
           'R',...
           'forcenorm',...    
           'score1',...
           'score2'
    };
%save_data(exper,resdir,indlist);  
save_data(scores,exper,resdir,indlist);

% indlist1 = {
%            'LI11',...
%            'LI12',...
%            'LI21',...
%            'LI22',...
%     };


% save_data(exper,resdir,);
 
                    

%% Plot time course of indicators
indlabel = { 'START TIME 1 [s]',...
             'START TIME 2 [s]',...
             'END TIME 1 [s]',...
             'END TIME 2 [s]',...
             'Partner 1 , min distance to VP1',...
             'Partner 1,min distance to VP2',...
             'Partner 2, min distance to VP2',...
             'Partner 2, min dstance to VP1',...
             'Partner 1, crossing time to VP1',...
             'Partner 1, crossing time to VP2',...
             'Partner 2, crossing time  to VP2',...
             'Partner 2, crossing time  to VP1',...
             'Partner 1,effort',...
             'Partner 2,effort',...
             'Partner 1,power',...
             'Partner 2,power',...
           };

indcatch = []; % index with which LI is calculated


% plot_indicator(exper,indlist,indlabel,indcatch,epsdir,figdir)
%  plot_adaptation(exper,indlist,indlabel)